In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
X=np.ones(4,dtype=np.int64)
X

array([1, 1, 1, 1])

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])
X = np.matrix(X)
X

matrix([[1, 2],
        [3, 4]])

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
X = np.linspace(3,10,num=50,endpoint=True)
X

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = x.flatten(order = 'F')
x

array([1, 4, 2, 5, 3, 6])

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.arange(1,10,1)
a,b,c = np.split(x,[4,6])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
X = np.array([[1, 2], [3, 4]])
X = np.matrix(X)
I = np.linalg.inv(X)
T = np.trace(X)
print(I)
print(T)

[[-2.   1. ]
 [ 1.5 -0.5]]
5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
X = np.array([[1, 4], [3, 1]])
s = np.sort(X, axis = 1)
s

array([[1, 4],
       [1, 3]])

Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
s = np.argsort(X, axis = 1)
s

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
#x = np.random.rand((2,5)) 
x = np.random.uniform(low=0, high=10, size=(2,5))
xmin, xmax = x.min(), x.max()
imin, imax = x.argmin(), x.argmax()
print(x)
print(xmin,xmax,imin,imax)

[[5.62092579 0.98435068 9.06130645 0.62865642 4.42902219]
 [6.69511639 5.32850217 8.67061201 1.96097122 8.45822474]]
0.628656416227853 9.06130645154628 3 2


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [ ]:
iris_2d_drop=iris_2d[~np.isnan(iris_2d).any(axis=1),:]


Find the correlation between first two columns.

In [ ]:
corr=np.corrcoef(iris_2d_drop[:,0],iris_2d_drop[:,1],rowvar=False)
corr[0,1]

-0.10936924995064937

Find the mean,median and standard deviation of column 3.

In [ ]:
mean=np.mean(iris_2d_drop[:,2])
median=np.median(iris_2d_drop[:,2])
std=np.std(iris_2d_drop[:,2])
print(mean, median, std)

3.758666666666666 4.35 1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
petallength=iris_2d_drop[:,0].astype('float')
sepal_length=iris_2d_drop[:,2].astype('float')
vol=(np.pi * petallength * (sepal_length**2))/3
vol = vol[:, np.newaxis]
iris_2d_new = np.append(iris_2d_drop, vol ,axis=1)
iris_2d_new

array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
        1.04677867e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        1.00572853e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        8.31789015e+00],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        1.08384947e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        1.02625360e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        1.63425650e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        9.44153312e+00],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        1.17809725e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        9.03103168e+00],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        1.15453530e+01],
       [5.40000000e+00, 3.7000

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [ ]:
len(np.unique(iris))

77

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
bin = np.digitize(iris_2d_drop[:,2].astype("float"), [0,3,5,10])
label = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petallength_text = [label[x] for x in bin]
petallength_text[:4]



['small', 'small', 'small', 'small']

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
x, freq = np.unique(iris[:, 2], return_counts=True)
x[np.argmax(freq)]

b'1.5'